Repository iamBedant/Multiplatform, pull requests merged in 2018-12, with the labels that each got.

#7 iOS gitignore added
  iosApp/.gitignore
Labels: enhancement

#9 some gitignore changes
  iosApp/.gitignore
Labels: bug

#6 basic ios poc done
  iosApp/Podfile
  iosApp/Podfile.lock
  iosApp/iosApp.xcodeproj/project.pbxproj
  iosApp/iosApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iosApp/iosApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iosApp/iosApp.xcodeproj/project.xcworkspace/xcuserdata/kuliza.xcuserdatad/UserInterfaceState.xcuserstate
  iosApp/iosApp.xcodeproj/xcuserdata/kuliza.xcuserdatad/xcschemes/xcschememanagement.plist
  iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  iosApp/iosApp/Assets.xcassets/Contents.json
  iosApp/iosApp/Assets.xcassets/right-arrow-forward.imageset/Contents.json
  iosApp/iosApp/Assets.xcassets/right-arrow-forward.imageset/right-arrow-forward@2x.png
  iosApp/iosApp/Assets.xcassets/right-arrow-forward.imageset/right-arrow-forward@3x.png
  iosApp/iosApp/Base.lproj/Main.storyboard
  iosApp/iosApp/Extensions/UILayer/UILayer+Color.swift
  iosApp/iosApp/Extensions/UIViewController/UIViewController+TextField.swift
  iosApp/iosApp/Fonts/RobotoMono-Light.ttf
  iosApp/iosApp/Fonts/RobotoMono-Regular.ttf
  iosApp/iosApp/Info.plist
  iosApp/iosApp/ViewController.swift
Labels: enhancement

#10 feat: Fixed iOS build after test
  app/src/commonMain/kotlin/sample/IosUtilities.kt
  app/src/commonMain/kotlin/sample/Utils.kt
  app/src/commonMain/kotlin/sample/presentation/MainPresenter.kt
  app/src/main/java/sample/MainActivity.kt
  iosApp/iosApp/BaseView.swift
  iosApp/iosApp/ViewController.swift
Labels: Fix

#12 Common tests
  app/src/commonMain/kotlin/sample/Const.kt
  app/src/commonMain/kotlin/sample/presentation/MainPresenter.kt
  app/src/commonTest/kotlin/sample/TestHelper.kt
  app/src/commonTest/kotlin/sample/presentation/MainPresenterTest.kt
  app/src/test/java/sample/MainPresenterTestHelper.kt
Labels: test
